name: reproducibility-rofl

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  release-rofl:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TODO: Move this to dedicated GitHub Action for CLI install.
      - name: Install Oasis CLI
        env:
          CLI_VERSION: 0.16.0
        run: |
          mkdir -p /tmp/oasis-cli
          cd /tmp/oasis-cli
          wget "https://github.com/oasisprotocol/cli/releases/download/v${CLI_VERSION}/oasis_cli_${CLI_VERSION}_linux_amd64.tar.gz" -O cli.tar.gz
          tar --strip-components 1 -xf cli.tar.gz
          echo "/tmp/oasis-cli" >> ${GITHUB_PATH}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          OUTPUT_IMAGE_NAME_PATH="/tmp/image-name" ./scripts/build_and_push_container_image.sh
          echo "EXPECTED_VERISAGE_IMAGE=$(cat /tmp/image-name)" >> ${GITHUB_ENV}

      - name: Verify image digest matches the compose file
        run: ./scripts/verify_container_image.sh

      - name: Build ROFL ORC for deployment, verify it matches the manifest
        run: oasis rofl build --deployment mainnet --verify
