name: reproducibility-docker

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      git_ref:
        description: "Branch or tag to verify"
        default: "master"
        required: true

jobs:
  check-container-reproducibility:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_GIT_REF: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.git_ref || 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DOCKER_GIT_REF }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and verify Docker image
        run: make verify-compose-image
